### ISSUE TITLE
styled-system refactor breakpoints to pixel

### ISSUE THREAD

**Issue by SuiOni** [pricelinelabs/design-system#312] opened 2018-05-13 22:30 UTC
Breakpoints in _styled-system_ are now pixel values by default.
That means that the default Priceline breakpoints as defined in the theme.js 
 with breakpoints = [32, 40, 48, 64] are interpreted as pixel values. 
That means when you use the responsive feature of _styled-system_ like fontSize={[6, 5, 4, 3, 2]} the breakpoints are 32px, 40px etc.

Changing the breakpoints to breakpoints = ['32em', '40em', '48em', '64em'] lets _styled-system_ interpret them as proper em, but then some Priceline components will fail e.g. the Hide components, which concatenates 'em' to the breakpoint resulting in something like "32emem"

My proposal: Either use pixel breakpoints and change '_em_' to '_px_' in the _media-queries_ or use 'em' for the breakpoint array but remove '_em_' from the _media-queries_

Not sure if I could explain myself well enough, as English is not my native language.
Cheers

**Comment by jxnblk** [comment] 2018-05-14 14:52
Maybe a duplicate of #252

**Comment by jxnblk** [comment] 2018-09-14 17:33
Closing this since this should be resolved in v2, but feel free to open a new issue if needed

**Closed by jxnblk** 2018-09-14 17:33 UTC
