### ISSUE TITLE
Consider height attribute for Box and derivatives

### ISSUE THREAD

**Issue by sdalonzo** [pricelinelabs/design-system#344] opened 2018-07-25 17:58 UTC
There are use cases where adding a height would be useful. In my specific example, a Google Map container needs a height in `vh` units.

**Comment by BeniCheni** [comment] 2018-08-16 19:05
Thanks for opening an issue @sdalonzo. Would you like to attend to the next design system WG meeting to discuss this open issue and bring it to action?

I've labeled this issue as "discussion" meanwhile. You can also ping the Slack design system channel for further meeting invite, or if you have further thoughts before the meeting, you can use the issue here to collaborate further.

**Comment by jxnblk** [comment] 2018-08-24 15:35
Duplicate of #101 

You can extend a component with styled-components to set height

**Closed by jxnblk** 2018-08-24 15:35 UTC
Labels: discussion
