### ISSUE TITLE
<Flex align=center /> sets align-items: center; and text-align: center;

### ISSUE THREAD

**Issue by jes708** [pricelinelabs/design-system#173] opened 2017-12-07 22:46 UTC
`<Flex align=center />` sets align-items: center; and text-align: center;

This is because `Flex` is an extension of `Box`.

On `Flex`, `align` means `align-items`
On `Box`, `align` means `text-align`

**Comment by jxnblk** [comment] 2017-12-08 15:08
Duplicate of #136

**Closed** 2017-12-11 18:53 UTC
Labels: bug
